# Generated by Django 5.0.7 on 2024-08-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('StudentId', models.AutoField(primary_key=True, serialize=False)),
                ('StudentName', models.CharField(max_length=255)),
                ('Studentaddress', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=255)),
            ],
        ),
    ]
